# Model Architecture
NUM_LAYERS: 6
D_MODEL: 512
NUM_HEADS: 8
DFF: 3072
DROPOUT: 0.15

# Data
MAX_LENGTH: 100
BATCH_SIZE: 48

# Training
EPOCHS: 30
LABEL_SMOOTHING: 0.1
WARMUP_STEPS: 25000
STEPS_PER_EPOCH: 8313